### ISSUE TITLE
data availability

### ISSUE THREAD

**Issue by sunnyosun** [broadinstitute/hdst#1]
Dear authors,

Could you please provide gene names in the *_unmodgtf_filtered_red_ut_HDST_final.tsv files you uploaded to single cell portal? Also I was not able to find segment ids in any of the files.

Thanks,
Sunny

**Comment by mssanjavickovic** [comment]
Hey Sunny, 

I've updated both now and correct files should be available on SCP

Thanks

Sanja

**Comment by sunnyosun** [comment]
Thank you so much Sanja for such a quick response!

Best,
Sunny
